version: "3.8"
services:
  docker-redis:
    image: redis:alpine
    expose:
      - 6479
    ports:
      - "6479:6379"
    networks:
      regservice-network:
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  docker-mysql:
    image: mysql/mysql-server:5.7.31
    container_name: docker-mysql
    volumes:
      - type: bind
        source: /home/dell/shreyas/Programming/Docker/mysqlws2
        target: /var/lib/mysql
    networks:
      regservice-network:
    environment:
      - MYSQL_DATABASE=/run/secrets/mysql_db_name
      - MYSQL_USER=/run/secrets/mysql_db_username
      - MYSQL_ROOT_PASSWORD=/run/secrets/mysql_db_password
      - MYSQL_ROOT_HOST='%'
    secrets:
      - mysql_db_name
      - mysql_db_username
      - mysql_db_password

    ports:
      - '3307:3306'
    restart:
      always
  docker-regservice:
    build:
      context: ./
      dockerfile: Dockerfile
    image: shred22/docker-regservice:1.2-SNAPSHOT
    container_name: docker-regservice
    networks:
      regservice-network:
    depends_on:
      - docker-redis
      - docker-mysql
    expose:
      - 7887
    ports:
      - 7887:7887
networks:
  regservice-network:

secrets:
  mysql_db_password:
    external: true
  mysql_db_username:
    external: true
  mysql_db_name:
    external: true
