server:
  port: 7887
spring:
  jta:
    enabled: true
    service: com.atomikos.icatch.standalone.UserTransactionServiceFactory
    max-actives: 200
    enable-logging: true
    atomikos:
      datasource:
        unique-resource-name: dataSourceOne
        max-pool-size: 5
        min-pool-size: 1
        max-life-time: 20000
        borrow-connection-timeout: 10000
        xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
        xa-properties:
          user: devuser
          password: password
          URL: jdbc:mysql://localhost:3306/bootdb?useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 7
        max-idle: 7
        max-wait: 1ms
        min-idle: 2
        shutdown-timeout: 200ms

  cache:
    type: redis
    redis:
      key-prefix: reg-
      use-key-prefix: true
      cache-null-values: false

  jackson:
    serialization:
      write-dates-as-timestamps: false

